[package]
name = "referential"
version = "0.1.0"
authors = ["Hugo van der Wijst <hugo@wij.st>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
