[package]
name = "referential_tests"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
referential = { version = "=0.1.0", path = "../referential" }

[features]
test-readme = []
